### ISSUE TITLE
Suggest adding shebang line to make bash happy

### ISSUE THREAD

**Issue by cwchien** [caryll/otfcc-cubic2quad#1]
After installing otfcc-c2q with npm, excute `otfcc-c2q` in **bash** yield the following error,

> line 1: syntax error near unexpected token `('`
> line 1: `var path = require('path');'

Tried several solutions, finally adding the shebang line to `c2q.js` fixed the problem,

``` javascript
#!/usr/bin/env node

var path = require('path');
...
```

OS: Ubuntu Linux 16.10 amd64
Bash: 4.3.46

P.S. Thanks a lot for the otfcc toolchains. :)

**Comment by be5invis** [comment]
fixed in 0.4.2.

**Comment by cwchien** [comment]
Thanks. :)
